### ISSUE TITLE
Charities

### ISSUE THREAD

**Issue by justmoon** [weusecoins/weusecoins#14]
I received this suggestion via mail a while ago:

----

Hello, I am contacting you with a suggestion for the site. I am one of the designers of http://bitcoinstocharity.org/ which is a site that gives a list of charities that accept Bitcoin donations. We are a non profit group that helps Bitcoin charities get noticed. To support charities that accept Bitcoin ,and the charities themselves, it would be a great help if a section of weusecoins included a list of Bitcoin accepting charities or even a link at the bottom of the website to bitcoinstocharity.org.

Some of the websites that accept Bitcoin donations are:

http://amani-kinderdorf.de/index.php?id=213
https://my.fsf.org/donate/other/
http://freedomboxfoundation.org/donate/
http://www.recycles.org/computer/donation/support/
https://vaizard.org/en/about/contacts/
http://shop.wikileaks.org/donate

All of these charities go to a great cause, and its important to support them, that way more charities and business will begin accepting the Bitcoin currency.

With the high volume of traffic on your website a simple link would surely be a great help to these charities.
 Many new Bitcoin users visit weusecoins.com for information about the Bitcoin currency, data concerning charities would be a great addition. Not many people in the Bitcoin world know which charities accept Bitcoin, which is why I believe this information should be provided on the site. Not only would this be a great help to users who wish to donate bitcoins, but also an amazing help to people aided by these charities. 

-----

I think it's an interesting idea. Please don't add this yet, but I wanted to open an issue, so we can start to discuss it. I think the main question is: How would we pick charities? How many should we list?

**Comment by sunnankar** [comment]
Outdated.
