### ISSUE TITLE
Free Bitcoins - First Google Form Broken

### ISSUE THREAD

**Issue by slatem** [weusecoins/weusecoins#28]
The first google form for embedding the widget is broken in Free Bitcoins section.

**Comment by JijoBose** [comment]
The price widget seems to be broken, stuck in "loading"

![Screenshot_2019-12-11 Bitcoin Price Ticker - Embed in your website and get free bitcoins](https://user-images.githubusercontent.com/13100108/70590841-005b9f80-1bfa-11ea-99b8-bf9731130994.png)
